definitions:
  main.PdfPreviewResponse:
    properties:
      images:
        items:
          type: string
        type: array
      pages:
        type: integer
    type: object
  main.PdfRequest:
    properties:
      data:
        items:
          type: string
        type: array
      download:
        type: boolean
      footer:
        type: string
      header:
        type: string
      marginBottom:
        type: number
      marginLeft:
        type: number
      marginRight:
        type: number
      marginTop:
        type: number
      paperSize:
        items:
          type: number
        type: array
    type: object
  main.PdfResponse:
    properties:
      components:
        items:
          type: string
        type: array
      url:
        type: string
    type: object
  main.PngRequest:
    properties:
      data:
        type: string
      download:
        type: boolean
      height:
        type: number
      scale:
        type: number
      width:
        type: number
      x:
        type: number
      "y":
        type: number
    type: object
  main.PngResponse:
    properties:
      png:
        type: string
      url:
        type: string
    type: object
info:
  contact: {}
paths:
  /pdf:
    post:
      consumes:
      - application/json
      - text/xml
      description: Submit urls/data to be converted to a PDF
      parameters:
      - description: The input todo struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/main.PdfRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.PdfResponse'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Submit urls/data to be converted to a PDF
  /png:
    post:
      consumes:
      - application/json
      - text/xml
      description: Submit a single url or data to be converted to a png
      parameters:
      - description: The input request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/main.PngRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.PngResponse'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Submit a single url or data to be converted to a png
  /preview:
    post:
      consumes:
      - application/json
      - text/xml
      description: Submit urls/data to be converted to a PDF and then one image per
        page
      parameters:
      - description: The input todo struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/main.PdfRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.PdfPreviewResponse'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Submit urls/data to be converted to a PDF and then one image per page
swagger: "2.0"
